[versions]
android-gradlePlugin = "7.4.2"
androidx-appcompat = "1.6.1"
byteunits = "0.9.1"
cardview = "1.0.0"
constraintlayout = "2.1.4"
coreKtx = "1.9.0"
emoji = "1.1.0"
firebase-analytics = "21.2.0"
firebase-auth = "21.1.0"
firebase-core = "21.1.1"
firebase-database = "20.1.0"
firebase-messaging = "23.1.2"
firebase-storage = "20.1.0"
firebase-ui-auth = "8.0.2"
firebase-ui-database = "8.0.2"
firebase-ui-storage = "8.0.2"
glide = "4.10.0"
google-android-material = "1.1.0"
google-gms = "4.3.15"
junit = "4.13.2"
kotlin = "1.8.10"
recyclerview = "1.3.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-emoji = { module = "androidx.emoji:emoji", version.ref = "emoji" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
byteunits = { module = "com.jakewharton.byteunits:byteunits", version.ref = "byteunits" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth" }
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebase-core" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebase-database" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebase-storage" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebase-ui-auth" }
firebase-ui-database = { module = "com.firebaseui:firebase-ui-database", version.ref = "firebase-ui-database" }
firebase-ui-storage = { module = "com.firebaseui:firebase-ui-storage", version.ref = "firebase-ui-storage" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-android-material = { module = "com.google.android.material:material", version.ref = "google-android-material" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-gms" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradlePlugin" }
google-gms = { id = "com.google.gms.google-services", version.ref = "google-gms" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
